language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  global:
    - secure: "OUiBO80s1IU/O4z88jei+ukCx5NgAk6UG/CbvrlUaF4MWfICtB7JVv03NND1\n0hD39lIUxA/l7zuAxwnLJvfI597jE0VLWPj8cXuiwb4IOKenFH+paU0b4Wm6\nhK903WqkVkFr6ZBHZWkBKrZ73+Cpog7NVyk6ku4kJ9R12+lbdRc="
    - secure: "RBBcQrsPM/g3JFLE7GQOngbMTRBiLpyHGmMErRe30T4FKyuZI7mUBc/P56Hj\nF50l2K9S3Fu1aIfE+ii9COiNJcNRjfXUFysqB4xVek9Qz06zNHUUd4ep1pNo\nDRqc3uAtxL1TxeGUst5Q8Ybobe/xc4/PRvxPD7CIRm/z+2LgrkU="
    - secure: "FM3bwYaSq2Tt5qNJza/fWeN3A58cAnj4dUaM3iFHXFjivRUBZe7dTYOqfdd8\nREGOurlvtdZZGGCmLq48TFF1tKy6FXfNa9luS68TTVFvWYRdVMlBHJ8STmCo\npW74lHoYSzaF2lCMAUPI69/xzlXDG4XTlU9ofsLREs0wCReEwEE="
    - secure: "lVbC9Y4Mo60z9cLLvwLut5b6dLkGqz+BBOaKvFRB6XMO4C0wbGVvF1478rQm\ntoZYFqTm1ydLVfe+8FGH70w0Osx5g9i/62sH1nDGmnrTl4yiH+wkz1ZngB4d\nd2Kd/n6Ve9g+Y2qCfNHJSla+CkuPhPoDwGENywZwWKhapFMZhGc="
script:
  - pip install tornado
  - python -m firstdata.tests